### PR TITLE
feat: turn off some rules

### PR DESCRIPTION
**Pull request by lucasvazq**
With this PR, I turn off some rules that are not required.

Here is the explanation:
- `no-import-assign`: It's configured with error in [eslint-config-airbnb](https://github.com/airbnb/javascript/blob/f3d3a075cda2acc02011e71991c10bb5b4a15278/packages/eslint-config-airbnb-base/rules/errors.js#L81), but marked as off in [plugin:@typescript-eslint/recommended](https://github.com/typescript-eslint/typescript-eslint/blob/0126b4f56f9197d561e90b09962ccceb4f88bc41/packages/eslint-plugin/src/configs/eslint-recommended.ts#L18)
- `no-setter-return`: It's configured with error in [eslint-config-airbnb](https://github.com/airbnb/javascript/blob/f3d3a075cda2acc02011e71991c10bb5b4a15278/packages/eslint-config-airbnb-base/rules/errors.js#L116), but marked as off in [plugin:@typescript-eslint/recommended](https://github.com/typescript-eslint/typescript-eslint/blob/0126b4f56f9197d561e90b09962ccceb4f88bc41/packages/eslint-plugin/src/configs/eslint-recommended.ts#L22)
- `import/no-named-as-default-member`: It's configured with error in [eslint-config-airbnb](https://github.com/airbnb/javascript/blob/f3d3a075cda2acc02011e71991c10bb5b4a15278/packages/eslint-config-airbnb-base/rules/imports.js#L62), but the following `typescript-eslint` documentation recommends turning it off: [TROUBLESHOOTING](https://github.com/typescript-eslint/typescript-eslint/blob/13583e65f5973da2a7ae8384493c5e00014db51b/docs/linting/TROUBLESHOOTING.md#eslint-plugin-import)

### CODE REVIEW

**Comment by iamturns** [comment]
Thanks for the PR @lucasvazq 

Sorry, but I don't think these rules belong in eslint-config-airbnb-typescript

An excerpt from the readme:

> **I wish this config would support [...]**
> 
> This config simply enhances the Airbnb with TypeScript support. It's not a single config to cater for all TypeScript linting requirements. For additional functionality, alter your ESLint config file. For example:
> ```
> module.exports = {
>   extends: [
>     'airbnb',
>     'airbnb-typescript',
>     'airbnb/hooks',
>     'plugin:@typescript-eslint/recommended',
>     'plugin:@typescript-eslint/recommended-requiring-type-checking',
>   ],
> };
> ```

**Comment by lucasvazq** [comment]
Hello @iamturns !

I understand your point. I just thought `eslint-config-airbnb-typescript` was copying some rules from `plugin:@typescript-eslint/recommended`. Why did I think this? Because I took a quick look and saw that [these rules (eslint-config-airbnb-typescript:master)](https://github.com/iamturns/eslint-config-airbnb-typescript/blob/master/lib/shared.js#L257) are very similar to the ones defined in [this file (plugin:@typescript-eslint/recommended:main)](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts#L10). Therefore, I had intuited that `eslint-config-airbnb-typescript` was outdated and I decided to create this PR to make an update.

If you still think you're right, feel free to close this PR.

**Comment by iamturns** [comment]
Hey @lucasvazq - great info, I appreciate all the links you added! I had embarssingly forgot about that chunk of code you listed 😊 

I've been thinking on what to do.

Option 1: I like the idea of removing those rules, keeping this set of rules as slim as possible, and leaving other concerns to better suited plugins, allowing flexibility in stacking eslint configs as they please.

Option 2: I like the idea of keeping these rules, because they are enabled within airbnb config, but nobody wants them enabled in a TypeScript world, which feels within the realms of this plugin.

I think Option 2 makes the most sense, and your PR is a great enhancement. Thank you!

**Pull request merged**
