### PR TITLE
Ruleset Improvement

### PR DESCRIPTION
**Pull request by deskoh**
As suggested in https://github.com/iamturns/eslint-config-airbnb-typescript/issues/16

### CODE REVIEW

**Comment by iamturns** [comment]
Hey @deskoh - thanks for the PR!

The goal of this project is to completely replicate typescript equivalent settings from `eslint-config-airbnb`. So even though the `no-extra-parens` and `no-magic-numbers` are set to `off`, I think the rules should still be replicated for 100% consistency and alignment with `eslint-config-airbnb`.

For reference:

`no-extra-parens` settings:
https://github.com/airbnb/javascript/blob/ab72ab9e90f403e90590f8815e0563248af10470/packages/eslint-config-airbnb-base/rules/errors.js#L62

`no-magic-numbers` settings:
https://github.com/airbnb/javascript/blob/ab72ab9e90f403e90590f8815e0563248af10470/packages/eslint-config-airbnb-base/rules/best-practices.js#L146

Great catch in the `quotes` setting, that should absolutely be in here! Happy to merge that in 👍

**Comment by deskoh** [comment]
@iamturns Updated.

**Comment by iamturns** [comment]
Thanks @deskoh !

**Pull request merged**
